Improve error message handling during chain handler execution (#201)
* Improve error message handling during chain handler execution

Reading chain errors tends to be a bit cryptic, mostly due to the fact
that the actual calling function has been funnelled/wrapped so many
times that it may be unclear exactly where an error has arisen.

Example:
```
  File "microcosm_pubsub/handlers/chain_handlers.py", line 42, in handle
    chain(**kwargs)
  File "microcosm_pubsub/chain/chain.py", line 68, in __call__
    res = func()
  File "microcosm_pubsub/chain/context_decorators.py", line 38, in decorate
    for arg_name, default in positional_args[len(args):]
  File "microcosm_pubsub/chain/context_decorators.py", line 39, in <dictcomp>
    if arg_name not in kwargs
  File "microcosm_pubsub/chain/context.py", line 20, in __getitem__
    return self.store[key]
KeyError: 'context_key'
```

Additionally, failures to find an attribute during `assign` calls end up
also missing helpful context:
```
  File "microcosm-pubsub/microcosm_pubsub/chain/statements/assign.py", line 28, in __call__
    value = value[part]
  File "site-packages/bravado_core/model.py", line 435, in __getitem__
    return self.__dict[property_name]
KeyError: 'id'
```

This changeset updates errors such that:
* On the inability to find a context key when evaluating a chained
function, both the key and the function are reported in the error
Example:
```
microcosm_pubsub.chain.exceptions.ContextKeyNotFound: Failed to find context_key `key` during evaluation of `func`
```

* If an attribute is unable to be found during assignment, both the
field and the parent are dutifully reported.
Example:
```
microcosm_pubsub.chain.exceptions.AttributeNotFound: Failed to find attribute `id` on `event`
```